export const playerIcons = [
  'fa-solid fa-hippo',
  'fa-solid fa-mug-hot',
  'fa-solid fa-fish',
  'fa-solid fa-user-secret',
  'fa-solid fa-cross',
  'fa-solid fa-rocket',
  'fa-solid fa-brain',
  'fa-brands fa-accessible-icon',
  'fa-solid fa-robot',
  'fa-solid fa-virus',
  'fa-solid fa-dragon',
  'fa-brands fa-square-js',
  'fa-solid fa-joint',
  'fa-solid fa-truck-monster',
  'fa-solid fa-recycle',
  'fa-solid fa-wine-bottle',
  'fa-solid fa-otter',
  'fa-solid fa-kiwi-bird',
  'fa-solid fa-venus',
  'fa-solid fa-user-injured',
  'fa-solid fa-transgender',
  'fa-solid fa-toilet-paper',
  'fa-solid fa-star-of-david',
  'fa-solid fa-spider',
  'fa-solid fa-spaghetti-monster-flying',
  'fa-solid fa-shrimp',
  'fa-solid fa-radiation',
  'fa-solid fa-pepper-hot',
  'fa-solid fa-mars',
  'fa-solid fa-hotdog',
  'fa-solid fa-horse',
  'fa-solid fa-frog',
  'fa-solid fa-dog',
  'fa-brands fa-jenkins',
  'fa-solid fa-bong',

  'fa-solid fa-ghost',
  'fa-solid fa-tornado',
  'fa-solid fa-satellite',
  'fa-solid fa-peace',
  'fa-solid fa-jedi',
  'fa-solid fa-hat-cowboy',
  'fa-solid fa-hand-middle-finger',
  'fa-regular fa-face-grin-tongue-wink',
  'fa-solid fa-drumstick-bite',
  'fa-solid fa-cannabis',
  'fa-solid fa-burger',
  'fa-brands fa-sticker-mule',
  'fa-brands fa-first-order',
  'fa-regular fa-hand-spock',
  'fa-regular fa-face-rolling-eyes',
  'fa-regular fa-face-angry',
];

export const playerIcons2 = [
  `<i class ="fa-solid fa-hippo"></i>`,
  `<i class ="fa-solid fa-mug-hot"></i>`,
  `<i class="fa-solid fa-fish"></i>`,
  `<i class="fa-solid fa-user-secret"></i>`,
  `<i class="fa-solid fa-cross"></i>`,
  `<i class="fa-solid fa-rocket"></i>`,
  `<i class="fa-solid fa-brain"></i>`,
  `<i class="fa-brands fa-accessible-icon"></i>`,
  `<i class="fa-solid fa-robot"></i>`,
  `<i class="fa-solid fa-virus"></i>`,
  `<i class="fa-solid fa-dragon"></i>`,
  `<i class="fa-brands fa-square-js"></i>`,
  `<i class="fa-solid fa-joint"></i>`,
  `<i class="fa-solid fa-truck-monster"></i>`,
  `<i class="fa-solid fa-recycle"></i>`,
  `<i class="fa-solid fa-wine-bottle"></i>`,
  `<i class="fa-solid fa-otter"></i>`,
  `<i class="fa-solid fa-kiwi-bird"></i>`,
  `<i class="fa-solid fa-venus"></i>`,
  `<i class="fa-solid fa-user-injured"></i>`,
  `<i class="fa-solid fa-transgender"></i>`,
  `<i class="fa-solid fa-toilet-paper"></i>`,
  `<i class="fa-solid fa-star-of-david"></i>`,
  `<i class="fa-solid fa-spider"></i>`,
  `<i class="fa-solid fa-spaghetti-monster-flying"></i>`,
  `<i class="fa-solid fa-shrimp"></i>`,
  `<i class="fa-solid fa-radiation"></i>`,
  `<i class="fa-solid fa-pepper-hot"></i>`,
  `<i class="fa-solid fa-mars"></i>`,
  `<i class="fa-solid fa-hotdog"></i>`,
  `<i class="fa-solid fa-horse"></i>`,
  `<i class="fa-solid fa-frog"></i>`,
  `<i class="fa-solid fa-dog"></i>`,
  `<i class="fa-brands fa-jenkins"></i>`,
  `<i class="fa-solid fa-bong"></i>`,

  `<i class="fa-solid fa-ghost"></i>`,
  `<i class="fa-solid fa-tornado"></i>`,
  `<i class="fa-solid fa-satellite"></i>`,
  `<i class="fa-solid fa-peace"></i>`,
  `<i class="fa-solid fa-jedi"></i>`,
  `<i class="fa-solid fa-hat-cowboy"></i>`,
  `<i class="fa-solid fa-hand-middle-finger"></i>`,
  `<i class="fa-regular fa-face-grin-tongue-wink"></i>`,
  `<i class="fa-solid fa-drumstick-bite"></i>`,
  `<i class="fa-solid fa-cannabis"></i>`,
  `<i class="fa-solid fa-burger"></i>`,
  `<i class="fa-brands fa-sticker-mule"></i>`,
  `<i class="fa-brands fa-first-order"></i>`,
  `<i class="fa-regular fa-hand-spock"></i>`,
  `<i class="fa-regular fa-face-rolling-eyes"></i>`,
  `<i class="fa-regular fa-face-angry"></i>`,
];
